server:
  port: 9000
  servlet:
    context-path: /foot

langchain4j:
  open-ai:
    chat-model:
      api-key: sk-173830c5bf894d97b35df2a23d107ab7
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      base-url: https://api.deepseek.com
      timeout: 60000
    streaming-chat-model:
      api-key: sk-173830c5bf894d97b35df2a23d107ab7
      model-name: deepseek-reasoner
      log-requests: true
      log-responses: true
      base-url: https://api.deepseek.com
      timeout: 60000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 13884399
    url: jdbc:mysql://127.0.0.1:3306/foot_core?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
football:
  api:
    # 彩票API
    match-list-url: "https://webapi.sporttery.cn/gateway/uniform/fb/getMatchDataPageListV1.qry?method=concern"
    fixed-bonus-url: "https://webapi.sporttery.cn/gateway/uniform/football/getFixedBonusV1.qry?clientCode=3001&matchId="
    search-odds-url: "https://webapi.sporttery.cn/gateway/uniform/football/searchOddsV1.qry?channel=c&type=&single=0&h=%s&a=%s&d=%s"
    result-history-url: "https://webapi.sporttery.cn/gateway/uniform/football/getResultHistoryV1.qry?sportteryMatchId=%s&termLimits=2&tournamentFlag=0&homeAwayFlag=0"
    # 飞书Webhook
    feishu-webhook-url: "https://open.feishu.cn/open-apis/bot/v2/hook/a553e701-25e0-4e58-ad26-920fde4c2631"

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      field-strategy: NOT_EMPTY
  configuration:
    call-setters-on-nulls: true
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.example.demo: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"